### ISSUE TITLE
Cannot divide by zero error when running Get-MFAReport

### ISSUE THREAD

**Issue by jschwager** [ReArmedHalo/DUST#5]
I believe this error occurs whenever there are more than 100 users being retrieved. Needs to be updated, perhaps remove progress percentages for now.

C:\Users\JaredSchwager> Get-MFAReport
WARNING: More results are available. Please specify one of the All or MaxResults parameters.
Attempted to divide by zero.
At C:\Users\JaredSchwager\GitHub\DUST\DUST\Public\Exchange Online\Get-MFAReport.ps1:20 char:5
+     $stepInterval = (100 / $users.Count)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], RuntimeException
    + FullyQualifiedErrorId : RuntimeException

**Comment by ReArmedHalo** [comment]
I am just going to remove the extra progress bars for now. Just a basic one showing that something is happening.

As for the WARNING, I fixed that just haven't committed it yet, I forgot the `-All:$true` parameter
